/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./components/layout/AppDrawer/AppDrawer.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader/AppHeader.vue')['default']
    AppIcon: typeof import('./components/ui/AppIcon/AppIcon.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout/AppLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewContainer: typeof import('./components/layout/ViewContainer/ViewContainer.vue')['default']
  }
}
